AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'images-s1918454'

  SnsTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: 'celebrity-recognizer-s1918454'








































